services:
  - type: web
    name: sistema-becas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir project app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
